### ISSUE TITLE
Create CITATION.cff

### ISSUE THREAD

**Issue by pancetta** [Parallel-in-Time/qmat#6]
For better citation I recommend creating and maintaining a CITATION.cff file, see https://citation-file-format.github.io/

**Comment by pancetta** [comment]
Also, visit https://github.com/Parallel-in-Time/qmat/community for further recommendations.

**Comment by tlunet** [comment]
Citation file will be added with the first beta release 0.1.0 and the link to zenodo

**Comment by tlunet** [comment]
Done
